# Header
menu:
  Home: /
  Archives: /archives
  Github: https://damao2017.github.io/
rss: /atom.xml

# Content
excerpt_link: More...
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
